'use client';

import { useState, useCallback } from 'react';
import { ChevronDown, ChevronUp, FileText, Download } from 'lucide-react';
import ReactMarkdown from 'react-markdown';
import { motion, AnimatePresence } from 'framer-motion';

interface Props {
  content: string;
  title?: string;
  timestamp: string;
}

function extractTitle(content: string): string {
  const match = content.match(/^#\s+(.+)/m);
  if (match) return match[1].trim();
  const firstLine = content.split('\n')[0].trim();
  if (firstLine.length < 80) return firstLine.replace(/^[#*]+\s*/, '');
  return 'Report';
}

function getPreview(content: string): string {
  const lines = content.split('\n').filter(l => l.trim() && !l.startsWith('#'));
  return lines.slice(0, 3).join('\n');
}

function isReport(content: string): boolean {
  if (content.length < 500) return false;
  const hasHeaders = /^#{1,3}\s/m.test(content);
  const hasBullets = /^[-*]\s/m.test(content);
  const hasSections = (content.match(/^#{1,3}\s/gm) || []).length >= 2;
  return hasHeaders && (hasBullets || hasSections);
}

export { isReport };

/** Convert markdown to simple HTML for PDF export */
function mdToHtml(md: string): string {
  return md
    .replace(/^### (.+)$/gm, '<h3>$1</h3>')
    .replace(/^## (.+)$/gm, '<h2>$1</h2>')
    .replace(/^# (.+)$/gm, '<h1>$1</h1>')
    .replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>')
    .replace(/\*(.+?)\*/g, '<em>$1</em>')
    .replace(/`(.+?)`/g, '<code>$1</code>')
    .replace(/^[-*] (.+)$/gm, '<li>$1</li>')
    .replace(/(<li>.*<\/li>\n?)+/g, (m) => `<ul>${m}</ul>`)
    .replace(/^\|(.+)\|$/gm, (_, row) => {
      const cells = row.split('|').map((c: string) => c.trim()).filter(Boolean);
      return '<tr>' + cells.map((c: string) => `<td>${c}</td>`).join('') + '</tr>';
    })
    .replace(/(<tr>.*<\/tr>\n?)+/g, (m) => `<table>${m}</table>`)
    .replace(/^(?!<[hulot])((?!<).+)$/gm, '<p>$1</p>')
    .replace(/<p>---<\/p>/g, '<hr/>')
    .replace(/<p><\/p>/g, '');
}

function generatePdfHtml(content: string, title: string, date: string): string {
  const bodyHtml = mdToHtml(content);
  return `<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>${title}</title>
<style>
  @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap');
  * { margin: 0; padding: 0; box-sizing: border-box; }
  @page { size: A4; margin: 40px 50px; }
  body {
    font-family: 'Inter', -apple-system, sans-serif;
    color: #0f0f1a;
    font-size: 13px;
    line-height: 1.7;
    background: #fff;
    -webkit-print-color-adjust: exact;
    print-color-adjust: exact;
  }
  .header {
    border-bottom: 2px solid #5b50d6;
    padding-bottom: 16px;
    margin-bottom: 24px;
  }
  .header h1 {
    font-size: 22px;
    font-weight: 800;
    color: #0f0f1a;
    letter-spacing: -0.5px;
  }
  .header .meta {
    font-size: 11px;
    color: #5a5a7a;
    margin-top: 4px;
  }
  .header .badge {
    display: inline-block;
    background: #5b50d6;
    color: white;
    font-size: 9px;
    font-weight: 700;
    padding: 2px 8px;
    border-radius: 4px;
    letter-spacing: 1px;
    text-transform: uppercase;
    margin-left: 8px;
    vertical-align: middle;
  }
  h1 { font-size: 20px; font-weight: 800; margin: 24px 0 12px; color: #0f0f1a; }
  h2 { font-size: 16px; font-weight: 700; margin: 20px 0 10px; color: #0f0f1a; border-bottom: 1px solid #e5e3df; padding-bottom: 6px; }
  h3 { font-size: 14px; font-weight: 600; margin: 16px 0 8px; color: #5a5a7a; }
  p { margin: 8px 0; }
  strong { color: #0f0f1a; }
  ul { margin: 8px 0 8px 20px; }
  li { margin: 4px 0; }
  code {
    background: #f5f4f1;
    padding: 1px 5px;
    border-radius: 3px;
    font-size: 12px;
    color: #5b50d6;
  }
  table {
    width: 100%;
    border-collapse: collapse;
    margin: 12px 0;
    font-size: 12px;
  }
  td, th {
    border: 1px solid #e5e3df;
    padding: 6px 10px;
    text-align: left;
  }
  tr:first-child td {
    font-weight: 600;
    background: #f5f4f1;
  }
  hr {
    border: none;
    border-top: 1px solid #e5e3df;
    margin: 20px 0;
  }
  .footer {
    margin-top: 32px;
    padding-top: 12px;
    border-top: 1px solid #e5e3df;
    font-size: 10px;
    color: #9090b0;
    text-align: center;
  }
</style>
</head>
<body>
  <div class="header">
    <h1>${title} <span class="badge">Agent Forge</span></h1>
    <div class="meta">Generated ${date} &middot; Powered by Agent Forge &middot; agentforge.systems</div>
  </div>
  ${bodyHtml}
  <div class="footer">
    This report was generated by Agent Forge AI research agents &middot; agentforge.systems
  </div>
</body>
</html>`;
}

export function ReportCard({ content, title, timestamp }: Props) {
  const [expanded, setExpanded] = useState(false);
  const resolvedTitle = title || extractTitle(content);
  const preview = getPreview(content);
  const date = new Date(timestamp).toLocaleDateString('en-US', {
    month: 'long', day: 'numeric', year: 'numeric'
  });

  const handleDownloadPdf = useCallback(() => {
    const html = generatePdfHtml(content, resolvedTitle, date);
    const printWindow = window.open('', '_blank');
    if (!printWindow) return;
    printWindow.document.write(html);
    printWindow.document.close();
    // Give fonts a moment to load
    setTimeout(() => {
      printWindow.print();
    }, 500);
  }, [content, resolvedTitle, date]);

  return (
    <div className="rounded-xl border border-border bg-card overflow-hidden max-w-2xl">
      {/* Header */}
      <div className="p-4 border-b border-border">
        <div className="flex items-center gap-3">
          <div className="w-9 h-9 rounded-lg bg-primary/10 border border-primary/20 flex items-center justify-center shrink-0">
            <FileText className="w-4 h-4 text-primary" />
          </div>
          <div className="flex-1 min-w-0">
            <div className="text-sm font-medium text-foreground truncate">{resolvedTitle}</div>
            <div className="text-xs text-muted-foreground">Generated {date}</div>
          </div>
        </div>
      </div>

      {/* Preview or Full Content */}
      <div className="p-4">
        <AnimatePresence mode="wait">
          {expanded ? (
            <motion.div
              key="full"
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              className="prose prose-sm prose-invert max-w-none [&>*:first-child]:mt-0 [&>*:last-child]:mb-0 [&_pre]:bg-background [&_pre]:border [&_pre]:border-border [&_pre]:rounded-lg [&_pre]:p-3 [&_code]:text-primary [&_code]:bg-primary/10 [&_code]:rounded [&_code]:px-1 [&_code]:py-0.5 [&_pre_code]:bg-transparent [&_pre_code]:p-0 [&_h1]:text-base [&_h2]:text-sm [&_h3]:text-sm [&_table]:text-xs"
            >
              <ReactMarkdown>{content}</ReactMarkdown>
            </motion.div>
          ) : (
            <motion.div
              key="preview"
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              className="text-sm text-muted-foreground leading-relaxed line-clamp-3"
            >
              {preview}
            </motion.div>
          )}
        </AnimatePresence>
      </div>

      {/* Actions */}
      <div className="px-4 pb-4 flex items-center gap-3">
        <button
          onClick={() => setExpanded(!expanded)}
          className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-medium border border-border bg-card hover:bg-card-hover text-foreground transition-all duration-200"
        >
          {expanded ? (
            <>
              <ChevronUp className="w-3.5 h-3.5" />
              Collapse
            </>
          ) : (
            <>
              <ChevronDown className="w-3.5 h-3.5" />
              Read Full Report
            </>
          )}
        </button>
        <button
          onClick={handleDownloadPdf}
          className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-medium border border-primary/20 bg-primary/5 hover:bg-primary/10 text-primary transition-all duration-200"
        >
          <Download className="w-3.5 h-3.5" />
          Download PDF
        </button>
      </div>
    </div>
  );
}
